### PR TITLE
Make double parsing locale independent (and faster)

### LINKED ISSUE #1566: parsing of doubles depends on locale
### issue
The parser assumes that a double has a `'.'` as the decimal separator:
https://github.com/symengine/symengine/blob/f7e253fdde1064584ea30728dd6430fc74d596d5/symengine/parser/parser.ih#L100
and if it finds one, it uses `strtod` to convert the string into a double.

This works fine, unless the locale has been set to one where a `','` is used as the separator instead, then `strtod` will incorrectly convert e.g. `3.142` to `3`, since it uses the locale defined decimal separator:
> `strtod` Parses the C-string str interpreting its content as a floating point number (according to the current locale) and returns its value as a double
http://www.cplusplus.com/reference/cstdlib/strtod/

### to reproduce
add the line
```
    std::setlocale(LC_NUMERIC, "de_DE.UTF-8");
```
to https://github.com/symengine/symengine/blob/f7e253fdde1064584ea30728dd6430fc74d596d5/symengine/tests/basic/test_parser.cpp#L586
and the "Parsing: doubles" test will fail.

### solution
One solution might be to set the locale to the default 'C' one within the parser:
```
std::locale old_locale = std::locale::global(std::locale::classic());
// parser code here
std::locale::global(old_locale);
```
Alternatively just adding a warning that the locale should not be set to something other than the default one somewhere in the docs/wiki would be nice to avoid other users from stumbling across this problem.

Thanks for a great library!

### PR DESCRIPTION
**Pull request by lkeegan**
- use `std::from_chars` instead of `strtod` to parse doubles if available (c++17 required)
  - otherwise falls back to previous `strtod` implementation
  - `std::from_chars` is locale independent and faster than `strtod`
- add more double parsing tests
- add double parsing google benchmarks
- resolves #1566

### CODE REVIEW

**Comment by rikardn** [comment]
`std::from_chars` has the potential of being the fastest possible parsing function. If I remember correctly the implementation of this in `libstdc++` was very delayed or even never implemented. I remember using a third party implementation once. Has it been implemented now in both gcc and clang?

**Comment by lkeegan** [comment]
- std::from_chars is significantly faster than strtod: https://quick-bench.com/q/sBL71XcFMu2N8MGvh5s_GoNHxD8
- this gives ~20% reduction in overall parse time in the benchmarks of expressions with many doubles

**Comment by lkeegan** [comment]
> `std::from_chars` has the potential of being the fastest possible parsing function. If I remember correctly the implementation of this in `libstdc++` was very delayed or even never implemented. I remember using a third party implementation once. Has it been implemented now in both gcc and clang?

According to https://github.com/fastfloat/fast_float their implementation is now part of gcc (12) and llvm (not sure exactly what version)

**Comment by rikardn** [comment]
Ok, nice. That was the implementation I was using. I think clang 15 supports it.

**Review by certik — APPROVED** [review]
Awesome, thanks!

File: symengine/parser/parser.cpp [hunk 1]
```diff
@@ -4,10 +4,29 @@
...
+#endif
 
 namespace SymEngine
 {
 
+static double string_to_double(const char *str, char **endptr)
+{
+#if ((defined(_MSVC_LANG) && _MSVC_LANG >= 201703L) || __cplusplus >= 201703L)
+    // use std::from_chars: locale-independent, non-allocating, non-throwing
+    double result{0.0};
```
Comment (rikardn) [inline symengine/parser/parser.cpp:18]: Do we expect this function to ever fail? If not do we need to initialize `result` here?

Comment (rikardn) [reply symengine/parser/parser.cpp:18]: Ok, I was just thinking that if the initialization doesn't matter because the parser guarantees that this is indeed a parsable string it could be removed to speed up the function a tiny bit more.

**Comment by lkeegan** [comment]
So it seems that just checking for c++17 at compile time was not sufficient as standard library support for `from_chars` (including parsing floating point values) is incomplete for:

- libstdc++ < 11
- macOS < 13.3
- libc++ < 14(?)

I've switched to just directly bundling and using the `fast_float` library instead (which is the underlying fast implementation of std::from_chars - thanks @rikardn!) and is available as a single header file.

**Comment by lkeegan** [comment]
@isuruf would you have time to take a look at this at some point? It would be nice to resolve #1566

File: symengine/CMakeLists.txt [hunk 2]
```diff
@@ -270,6 +270,11 @@ if (NOT WITH_SYSTEM_CEREAL)
   set(HEADERS ${HEADERS} ${CEREAL_HEADERS})
 endif()
 
+if (NOT WITH_SYSTEM_FASTFLOAT)
+    file(GLOB_RECURSE FASTFLOAT_HEADERS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "utilities/fast_float/include/*")
+    set(HEADERS ${HEADERS} ${FASTFLOAT_HEADERS})
+endif()
+
```
Comment (isuruf) [inline symengine/CMakeLists.txt:277]: Why do we need to install this? They are not exposed by any symengine header right?

Comment (lkeegan) [reply symengine/CMakeLists.txt:277]: You're right - we don't need to install this, sorry!

**Comment by isuruf** [comment]
Thanks
