### PR TITLE
fix small bug with construction of flint poly; closes #878

### LINKED ISSUE #878: The series of (1+x)^0 appears to result in other things than 1
cc @rwst , 
The series of `(1+x)^0` does not result in 1.  I guess the problem might be with this https://github.com/symengine/symengine/blob/master/symengine/series_flint.cpp#L126
as it passes an `integer` directly into the fp_t().

### PR DESCRIPTION
**Pull request by rwst**

### CODE REVIEW

File: symengine/tests/basic/test_series_expansion_URatF.cpp [hunk 1]
```diff
@@ -70,11 +70,14 @@ TEST_CASE("Expression series expansion: Add ", "[Expansion of Add]")
     auto z = add(integer(1), x);
     z = sub(z, pow(x, integer(2)));
     z = add(z, pow(x, integer(4)));
+    auto z1 = pow(add(integer(1), x), integer(0));
```
Comment (isuruf) [inline symengine/tests/basic/test_series_expansion_URatF.cpp]: This doesn't really check the bug, but I doubt we can trigger the bug anyway.
